# Generated by Django 4.0.3 on 2022-03-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
    ]
