# Generated by Django 4.0.3 on 2022-03-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0002_remove_store_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='google_book_id',
        ),
    ]
