# Generated by Django 4.0.3 on 2022-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0003_rename_book_id_book_google_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='default author', max_length=100),
            preserve_default=False,
        ),
    ]
